version: "3"
services:
  web:
    build: ./app
    ports:
      - "5000:5000"
    volumes:
      - ./app/database.db:/app/database.db  # Persist SQLite database
    environment:
      - FLASK_ENV=development
    restart: always
